package rpis61.barinova.wdad.learn.xml.librarystaff;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 08:29:37 PM SAMT 
//

import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "author",
    "name",
    "printyear",
    "genre"
})
@XmlRootElement(name = "book")
public class Book  implements Serializable {

    @XmlElement(required = true)
    protected Author author;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String printyear;
    @XmlElement(required = true)
    protected Genre genre;
    @XmlTransient
    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link Author }
     *     
     */
    public Author getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link Author }
     *     
     */
    public void setAuthor(Author value) {
        this.author = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the printyear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintyear() {
        return printyear;
    }

    /**
     * Sets the value of the printyear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintyear(String value) {
        this.printyear = value;
    }

    /**
     * Gets the value of the genre property.
     * 
     * @return
     *     possible object is
     *     {@link Genre }
     *     
     */
    public Genre getGenre() {
        return genre;
    }

    /**
     * Sets the value of the genre property.
     * 
     * @param value
     *     allowed object is
     *     {@link Genre }
     *     
     */
    public void setGenre(Genre value) {
        this.genre = value;
    }
    public Book(Author author, String name, String printyear, Genre genre) {
        this.author = author;
        this.name = name;
        this.printyear = printyear;
        this.genre = genre;
    }
    Book(){
        this(null, null,null,null);
    }
}
