package rpis61.barinova.wdad.learn.xml.librarystaff;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 08:29:37 PM SAMT 
//


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;
import java.time.LocalDate;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "takedate")
public class Takedate  implements Serializable {

    @XmlAttribute(name = "day", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String day;
    @XmlAttribute(name = "month", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String month;
    @XmlAttribute(name = "year", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String year;

    /**
     * Gets the value of the day property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDay() {
        return day;
    }

    /**
     * Sets the value of the day property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDay(String value) {
        this.day = value;
    }

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonth(String value) {
        this.month = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYear(String value) {
        this.year = value;
    }

//    Takedate(LocalDate date){
//        this.day = Integer.toString( date.getDayOfMonth());
//        this.month = Integer.toString(  date.getMonthValue());
//        this.year = Integer.toString( date.getYear());
//    }


        Takedate(String date){ // for format yyyy-mm-dd
        this.day = date.split("-")[2];
        this.month = date.split("-")[1];
        this.year = date.split("-")[0];
    }

    Takedate(){
        day = "";
        month = "";
        year = "";
    }

    public long toEpochDay(){
        return LocalDate.of(Integer.parseInt(year), Integer.parseInt(month),Integer.parseInt(day)).toEpochDay();
    }
}
