//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.03 at 03:18:31 PM SAMT 
//


package rpis61.barinova.wdad.data.managers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "policypath",
    "usecodebaseonly"
})
@XmlRootElement(name = "client")
public class Client {

    @XmlElement(required = true)
    protected String policypath;
    @XmlElement(required = true)
    protected String usecodebaseonly;

    /**
     * Gets the value of the policypath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicypath() {
        return policypath;
    }

    /**
     * Sets the value of the policypath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicypath(String value) {
        this.policypath = value;
    }

    /**
     * Gets the value of the usecodebaseonly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsecodebaseonly() {
        return usecodebaseonly;
    }

    /**
     * Sets the value of the usecodebaseonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsecodebaseonly(String value) {
        this.usecodebaseonly = value;
    }

}
